### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'counts' in undefined

### ISSUE THREAD

**Issue by kanongil** [apache/nano#313]
Regression in 6.2.0 from c03b5528b6b0759f7e001b722199f824163ad3a0. The patch breaks lookups that has neither `qs` or `callback` set.

**Comment by jo** [comment]
Thanks for catching this!

**Comment by WaldoJeffers** [comment]
Yup, I have the same issue. For example, if do `db.viewWithList('design','view','list').pipe(...)`, I get this error : `TypeError: Cannot use &#39;in&#39; operator to search for 'counts' in undefined`.

**Comment by MatthieuLemoine** [comment]
I also have the issue as @WaldoJeffers when using viewWithList.

**Comment by mgarchagudashvili** [comment]
I have the same issue when requesting views

**Comment by mgarchagudashvili** [comment]
I have the same issue when using view(ddoc, viewName, meta, callback).

**Comment by bedney** [comment]
Still seeing this. Would a PR help?

**Comment by carlosduclos** [comment]
This repository has been merged into apache/couchdb-nano, please continue the discussion [here](https://github.com/apache/couchdb-nano/issues/22)
